import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import topicsRouter from "./topics.js";
import newsRouter from "./news.js";
import telegramRouter from "./telegram.js";
import deliveryRouter from "./delivery.js";
import costsRouter from "./costs.js";
import feedRouter from "./feed.js";
import alertsRouter from "./alerts.js";
import analyticsRouter from "./analytics.js";
import preferencesRouter from "./preferences.js";
import debugRouter from "./debug.js";
import feedQualityRouter from "./feedQuality.js";
import adaptiveRouter from "./adaptive.js";
import narrativesRouter from "./narratives.js";
import proactiveIntelligenceRouter from "./proactiveIntelligence.js";
import adminNarrativesRouter from "./adminNarratives.js";
import habitRouter from "./habit.js";
import multimodalRouter from "./multimodal.js";
import identityRouter from "./identity.js";
import economicsRouter from "./economics.js";
import knowledgeCompoundRouter from "./knowledgeCompound.js";
import waitlistRouter from "./waitlist.js";
import signalModeRouter from "./signalMode.js";
import systemIntelligenceRouter from "./systemIntelligence.js";
import efficiencyAdminRouter from "./efficiencyAdmin.js";
import sprint18AdminRouter from "./sprint18Admin.js";
import eventTrackingRouter from "./eventTracking.js";
import adminAnalyticsRouter from "./adminAnalytics.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(topicsRouter);
router.use(newsRouter);
router.use(telegramRouter);
router.use(deliveryRouter);
router.use(costsRouter);
router.use(feedRouter);
router.use(alertsRouter);
router.use(analyticsRouter);
router.use(preferencesRouter);
router.use(debugRouter);
router.use(feedQualityRouter);
router.use(adaptiveRouter);
router.use(narrativesRouter);
router.use(proactiveIntelligenceRouter);
router.use(adminNarrativesRouter);
router.use(habitRouter);
router.use(multimodalRouter);
router.use(identityRouter);
router.use(economicsRouter);
router.use(knowledgeCompoundRouter);
router.use(waitlistRouter);
router.use(signalModeRouter);
router.use(systemIntelligenceRouter);
router.use(efficiencyAdminRouter);
router.use(sprint18AdminRouter);
router.use(eventTrackingRouter);
router.use(adminAnalyticsRouter);

export default router;
